version: "3.7"

services:

  form-drafts-web-component:
    image: form-drafts-web-component:1.0.0
    build: ./form-drafts-web-component
    ports:
      - 3001:8080

  movie-database:
    image: movie-database:1.0.0
    build: ./movie-database
    ports:
      - 3002:3000

  movie-reviews:
    image: movie-reviews:1.0.0
    build: ./movie-reviews
    ports:
      - 3003:3000
