version: "3.7"

services:

  movie-database:
    image: movie-database
    build:
      context: ./movie-database
      dockerfile: ../Dockerfile
      target: back-end_front-end_components
      args:
        APP_NAME: movie-database
    ports:
      - 3002:3000

  movie-reviews:
    image: movie-reviews
    build:
      context: ./movie-reviews
      dockerfile: ../Dockerfile
      target: back-end_front-end
      args:
        APP_NAME: movie-reviews
    ports:
      - 3003:3000
    depends_on:
      - movie-database
    command: ["./wait-for-it.sh", "movie-database:3000", "--", "npm", "start"]
