version: "3.7"

services:

  movie-components:
    image: movie-components:1.0.0
    build: ./movie-components
    ports:
      - 3001:8080

  movie-database:
    image: movie-database:1.0.0
    build:
      context: ./movie-database
      dockerfile: ../Dockerfile
    ports:
      - 3002:3000

  movie-reviews:
    image: movie-reviews:1.0.0
    build:
      context: ./movie-reviews
      dockerfile: ../Dockerfile
    ports:
      - 3003:3000
