/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  Movie,
} from './models/movie';

export namespace Components {
  interface AddMovieComponent {
    /**
    * Optional property that allows to control whether the form's cancel button has to be rendered or not.
    */
    'allowCancel': boolean;
    /**
    * Optional property that allows to define the styling of the component. Possible values: `blue`, `green`.
    */
    'mode': string;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLAddMovieComponentElement extends Components.AddMovieComponent, HTMLStencilElement {}
  var HTMLAddMovieComponentElement: {
    prototype: HTMLAddMovieComponentElement;
    new (): HTMLAddMovieComponentElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'add-movie-component': HTMLAddMovieComponentElement;
    'my-component': HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface AddMovieComponent {
    /**
    * Optional property that allows to control whether the form's cancel button has to be rendered or not.
    */
    'allowCancel'?: boolean;
    /**
    * Optional property that allows to define the styling of the component. Possible values: `blue`, `green`.
    */
    'mode'?: string;
    /**
    * Events emitted at every successful movie creation.
    */
    'onMovieCreated'?: (event: CustomEvent<Movie>) => void;
    /**
    * Event emitted everytime the user clicks on the cancel button.
    */
    'onMovieCreationCanceled'?: (event: CustomEvent<never>) => void;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'add-movie-component': AddMovieComponent;
    'my-component': MyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'add-movie-component': LocalJSX.AddMovieComponent & JSXBase.HTMLAttributes<HTMLAddMovieComponentElement>;
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
    }
  }
}


